### ISSUE TITLE
Can't find option in settings

### ISSUE THREAD

**Issue by inhahe** [sybrew/emoji-settings#5]
I just installed emoji-settings on my blog at wordpress.com, and I don't see any setting having anything to do with emojis under Settings->Writing. Halp!

**Comment by sybrew** [comment]
Hello!

At the top right, you have the "View" button. Could you try "Classic view" and see if you can find the option then?

**Comment by inhahe** [comment]
Sorry, I couldn't find a "view" button. Where is it exactly (what page on Wordpress, in which position in the line of icons) and what does it look like? Thanks

**Comment by sybrew** [comment]
Hi again, @inhahe!

The "view" button should be at the top right of your screen. The emoji settings toggle should be available at "WP Admin > Settings > Writing."

If this View toggle or the Emoji Settings toggle aren't there, you may need to consult with WordPress.com support—they treat plugin developers like second-rank citizens, and these discrepancies between WordPress.org and WordPress.com aren't communicated with us. I also cannot test my plugins on their network, even though they host my software and ask you to pay to use it while it's freely available; I'm also seeing none of the money they make off of my software.

**Comment by inhahe** [comment]
Ah, thanks for the reply. And sorry to hear about Wordpress' treatment of you ;//
I found the view button! I didn't know it was only available on the Settings page. 
And when I changed it to Classic, the emojis option was there.
Thx again.
